# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"
# platform :osx, "10.8"

platform :ios, "7.0"
inhibit_all_warnings!

target "ShowTracker" do
    pod 'AFNetworking', '>= 2.2'
    pod 'SSToolkit', '>= 1.0'
    pod 'Nimbus/AttributedLabel', '>= 1.2'
end

